# fly.toml app configuration file generated for inthedark-proxy on 2026-02-03T19:40:46+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'inthedark-proxy'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3128
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 3128

  [[services.ports]]
    port = 3128

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
